server:
  port: 8088
mybatis:
  type-aliases-package: com.example.mybatis.demo.entity
  mapper-locations: classpath:mappers/*.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flyway_test?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:







#spring:
#  profiles:
#    active: dev
